name = "BoffinStuff"
repo = "https://github.com/wildart/BoffinStuff.git"
uuid = "78be8f42-883b-441c-9ce8-714b7da9a48e"
description = "This registry contains various research projects."

[packages.173e3a66-dd8a-5f2e-8a96-8b7ddc4d534d]
name = "LMCLUS"
path = "LMCLUS"

[packages.a4b5195f-7e50-4300-9f38-3baf1bf3ac9e]
name = "ClusterComplex"
path = "ClusterComplex"

[packages.ba71f38f-f508-439b-ac77-437f86a20aa1]
name = "SmithNormalForm"
path = "SmithNormalForm"

[packages.9393a4d0-be1e-45b0-9991-b60434c721e6]
name = "ComputationalHomology"
path = "ComputationalHomology"
