name = "BoffinStuff"
repo = "https://github.com/wildart/BoffinStuff.git"
uuid = "78be8f42-883b-441c-9ce8-714b7da9a48e"
description = "This registry contains various research projects."

[packages.ba71f38f-f508-439b-ac77-437f86a20aa1]
name = "SmithNormalForm"
path = "SmithNormalForm"
